TITLE Mod file for component: Component(id=generic_muscle_iaf_cell type=iafActivityCell)

COMMENT

    This NEURON file has been generated by org.neuroml.export (see https://github.com/NeuroML/org.neuroml.export)
         org.neuroml.export  v1.11.0
         org.neuroml.model   v1.11.0
         jLEMS               v0.12.0

ENDCOMMENT

NEURON {
    POINT_PROCESS generic_muscle_iaf_cell
    
    
    NONSPECIFIC_CURRENT i                   : To ensure v of section follows v_I
    RANGE tau1                              : parameter
    RANGE leakConductance                   : parameter
    RANGE leakReversal                      : parameter
    RANGE thresh                            : parameter
    RANGE reset                             : parameter
    RANGE C                                 : parameter
    RANGE iSyn                              : exposure
    RANGE iMemb                             : exposure
    RANGE target                            : derived variable
    
}

UNITS {
    
    (nA) = (nanoamp)
    (uA) = (microamp)
    (mA) = (milliamp)
    (A) = (amp)
    (mV) = (millivolt)
    (mS) = (millisiemens)
    (uS) = (microsiemens)
    (nF) = (nanofarad)
    (molar) = (1/liter)
    (kHz) = (kilohertz)
    (mM) = (millimolar)
    (um) = (micrometer)
    (umol) = (micromole)
    (pC) = (picocoulomb)
    (S) = (siemens)
    
}

PARAMETER {
    
    tau1 = 50 (ms)                         : was: 0.05 (time)
    leakConductance = 1.0E-4 (uS)          : was: 1.0000000000000002E-10 (conductance)
    leakReversal = -50 (mV)                : was: -0.05 (voltage)
    thresh = -30 (mV)                      : was: -0.03 (voltage)
    reset = -50 (mV)                       : was: -0.05 (voltage)
    C = 0.003 (nF)                         : was: 3.0E-12 (capacitance)
}

ASSIGNED {
    v (mV)
    i (nA)                                 : the point process current 
    
    v_I (mV/ms)                             : for rate of change of voltage 
    iSyn (nA)                               : derived variable
    iMemb (nA)                              : derived variable
    target                                  : derived variable
    rate_v (mV/ms)
    rate_activity (/ms)
    
}

STATE {
    activity  : dimension: none
    
}

INITIAL {
    rates()
    rates() ? To ensure correct initialisation.
    
    net_send(0, 1) : go to NET_RECEIVE block, flag 1, for initial state
    
}

BREAKPOINT {
    
    SOLVE states METHOD cnexp
    
    if (activity  < 0) {
        activity = 0 ? standard OnCondition
    }
    
    
    i = v_I * C
}

NET_RECEIVE(flag) {
    
    if (flag == 1) { : Setting watch for top level OnCondition...
        WATCH (v >  thresh) 1001
    }
    if (flag == 1001) {
    
        v = reset
    
        v_I = 0 : Setting rate of change of v to 0
    }
    if (flag == 1) { : Set initial states
    
        v = reset
    }
    
}

DERIVATIVE states {
    rates()
    activity' = rate_activity 
    
}

PROCEDURE rates() {
    
    ? DerivedVariable is based on path: synapses[*]/i, on: Component(id=generic_muscle_iaf_cell type=iafActivityCell), from synapses; null
    iSyn = 0 ? Was: synapses[*]_i but insertion of currents from external attachments not yet supported ? path based, prefix = 
    
    iMemb = leakConductance  * (  leakReversal   - v) +  iSyn ? evaluable
    target = (v -   reset  ) / (  thresh   -   reset  ) ? evaluable
    rate_v = iMemb  /  C ? Note units of all quantities used here need to be consistent!
    rate_activity = (  target  -  activity  )/  tau1 ? Note units of all quantities used here need to be consistent!
    
    v_I = -1 * rate_v
     
    
}

